### create
POST localhost:8080/api/v1/channel/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIwMTY0MDcsImlkIjo1LCJlbWFpbCI6InJ1bm5lcnBybzE5OTBAZ21haWwuY29tIiwiZXhwIjoxNjkyMTAyODA3LCJpc3MiOiJ5b3VfdHViZV91eiB0ZXN0In0.Jzw3jPM_8vISkAEJLPq3E9B2U1kZtoUbW0pOI5-S0ivPAkaMwmrIZ2h3e3sddBeIY6R9kLa2zQdexKtKNxAt0g

{
  "name": "ru.tv",
  "description": "musiqa kanali",
  "imageId": "367551be-446c-4ad6-9b71-0fff2be204de",
  "bannerId": "6c102cc5-b45a-46f7-b7ec-51a57bf22acb"
}

###update name
PUT localhost:8082/api/v1/channel/updateName?oldName=ru.tv&newName=tarona.tv
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIwMDMzNzQsImlkIjo2LCJlbWFpbCI6ImRpeW9yYmVraGFtaWRvdjY4MkBnbWFpbC5jb20iLCJleHAiOjE2OTIwODk3NzQsImlzcyI6InlvdV90dWJlX3V6IHRlc3QifQ.GGVoGdb0xhFt7XsyFGZ-3g_McplTvTm_o4hibUyWqzXe9kV-1i26z4H_mXbp5BC9XTSjlwANRICowntBHJgoNg

### update image
PUT localhost:8082/api/v1/channel/updateImage?name=tarona.tv&imageId=ab8f9536-88c2-4f4c-80ad-1cd3eb6d36fa
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIwMDMzNzQsImlkIjo2LCJlbWFpbCI6ImRpeW9yYmVraGFtaWRvdjY4MkBnbWFpbC5jb20iLCJleHAiOjE2OTIwODk3NzQsImlzcyI6InlvdV90dWJlX3V6IHRlc3QifQ.GGVoGdb0xhFt7XsyFGZ-3g_McplTvTm_o4hibUyWqzXe9kV-1i26z4H_mXbp5BC9XTSjlwANRICowntBHJgoNg

###update banner
PUT localhost:8082/api/v1/channel/updateBanner?name=tarona.tv&bannerId=ab8f9536-88c2-4f4c-80ad-1cd3eb6d36fa
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIwMDMzNzQsImlkIjo2LCJlbWFpbCI6ImRpeW9yYmVraGFtaWRvdjY4MkBnbWFpbC5jb20iLCJleHAiOjE2OTIwODk3NzQsImlzcyI6InlvdV90dWJlX3V6IHRlc3QifQ.GGVoGdb0xhFt7XsyFGZ-3g_McplTvTm_o4hibUyWqzXe9kV-1i26z4H_mXbp5BC9XTSjlwANRICowntBHJgoNg

###pagination
GET localhost:8082/api/v1/channel/pagination?page=1&size=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIwMDgzMTgsImlkIjoyLCJlbWFpbCI6ImRpeW9yYmVraGFtaWRvdjA1MTlAZ21haWwuY29tIiwiZXhwIjoxNjkyMDk0NzE4LCJpc3MiOiJ5b3VfdHViZV91eiB0ZXN0In0.mO6Hz5_qH2US7zxDMSIfipfxCqMEuh0RHjJAzpKMv-nx4Qd9Px1tgMivcK4WmLvyN8zYfsGdd919ijyQ8l4aBw

### get by id
GET localhost:8082/api/v1/channel/getById/0c5452db-2fda-4da2-b339-b3302ff35282
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIwMDgzMTgsImlkIjoyLCJlbWFpbCI6ImRpeW9yYmVraGFtaWRvdjA1MTlAZ21haWwuY29tIiwiZXhwIjoxNjkyMDk0NzE4LCJpc3MiOiJ5b3VfdHViZV91eiB0ZXN0In0.mO6Hz5_qH2US7zxDMSIfipfxCqMEuh0RHjJAzpKMv-nx4Qd9Px1tgMivcK4WmLvyN8zYfsGdd919ijyQ8l4aBw

### change status
PUT localhost:8082/api/v1/channel/changeStatus/0c5452db-2fda-4da2-b339-b3302ff35282
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIwMDgzMTgsImlkIjoyLCJlbWFpbCI6ImRpeW9yYmVraGFtaWRvdjA1MTlAZ21haWwuY29tIiwiZXhwIjoxNjkyMDk0NzE4LCJpc3MiOiJ5b3VfdHViZV91eiB0ZXN0In0.mO6Hz5_qH2US7zxDMSIfipfxCqMEuh0RHjJAzpKMv-nx4Qd9Px1tgMivcK4WmLvyN8zYfsGdd919ijyQ8l4aBw


###get channels
GET localhost:8082/api/v1/channel/getChannels
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTIwMDMzNzQsImlkIjo2LCJlbWFpbCI6ImRpeW9yYmVraGFtaWRvdjY4MkBnbWFpbC5jb20iLCJleHAiOjE2OTIwODk3NzQsImlzcyI6InlvdV90dWJlX3V6IHRlc3QifQ.GGVoGdb0xhFt7XsyFGZ-3g_McplTvTm_o4hibUyWqzXe9kV-1i26z4H_mXbp5BC9XTSjlwANRICowntBHJgoNg
